# Generated by Django 5.1.2 on 2024-12-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='interval',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backtest',
            name='period',
            field=models.CharField(default='1m', max_length=100),
            preserve_default=False,
        ),
    ]
