# Generated by Django 5.1.2 on 2025-01-28 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtestapp', '0007_result_process_list'),
        ('strategyapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='strategy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtestapp_backtests', to='strategyapp.strategy'),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtestapp_backtests', to=settings.AUTH_USER_MODEL),
        ),
    ]
