# Generated by Django 5.1.2 on 2025-02-10 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='candles',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
            preserve_default=False,
        ),
    ]
