# Generated by Django 5.1.2 on 2025-01-28 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botingapp', '0001_initial'),
        ('strategyapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Backtest',
            new_name='Bot',
        ),
    ]
