# Generated by Django 5.1.2 on 2025-01-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botingapp', '0002_rename_backtest_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='percentage_of_portfolio',
        ),
        migrations.AddField(
            model_name='bot',
            name='day_first_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='first_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='last_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='month_first_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='week_first_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
