# Generated by Django 5.1.2 on 2025-01-29 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botingapp', '0004_bottransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_list', models.TextField(help_text='JSON formatında bot mevduat listesi')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='botingapp.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_situations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Durumu',
                'verbose_name_plural': 'Bot Durumları',
                'ordering': ['-last_update'],
            },
        ),
    ]
