# Generated by Django 5.1.2 on 2025-02-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botingapp', '0005_botsituation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botsituation',
            options={'ordering': ['-last_update'], 'verbose_name': 'Bot Situation', 'verbose_name_plural': 'Bot Situations'},
        ),
    ]
