# Generated by Django 5.1.2 on 2025-02-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionapp', '0002_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
