# Generated by Django 5.1.2 on 2025-02-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectionapp', '0003_alter_userbalance_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbalance',
            old_name='amount',
            new_name='balance',
        ),
    ]
